name: flashfeed
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: 1.3.0
  cached_network_image: 3.2.3
  json_annotation: 4.8.0
  easy_splash_screen: 1.0.4
  webview_flutter: 4.0.7
  carousel_slider: 4.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  build_runner: 2.3.3
  json_serializable: 6.6.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

